### ISSUE TITLE
OBS Studio doesnt work with NVENC 

### ISSUE THREAD

**Issue by iWeaker4you** [flathub/com.obsproject.Studio#117] opened 2021-04-03 06:26 UTC
Debian 11 Testing
Flatpak version 1.10.2-1
Install OBS using this guide https://flathub.org/apps/details/com.obsproject.Studio
When I start OBS for the first time, I detect that I had NVENC without any problem and I install the necessary dependencies correctly, but when recording, it gives me an NVENC error

I have installed the dependencies on my Debian correctly, the packages are
libnvcuvid1 and libnvidia-encode1

"Failed to open NVENC"

![113466878-00397180-93f4-11eb-84df-7815a9860be5](https://user-images.githubusercontent.com/49424816/113470477-dccdf100-940a-11eb-8457-1e168a382d87.png)

**Comment by dgcampea** [comment] 2021-04-07 11:01
https://packages.debian.org/bullseye/libcuda1
Is the driver installed on the host and did you reboot before opening OBS?

**Comment by GeorgesStavracas** [comment] 2021-04-18 18:14
Duplicate of #83

**Closed** 2021-04-18 18:14 UTC
