### ISSUE TITLE
Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.

### ISSUE THREAD

**Issue by dmarrazzo** [flathub/com.obsproject.Studio#78] opened 2020-08-31 18:28 UTC
Installed version:
```
OBS Studio            com.obsproject.Studio                  25.0.8          beta          flathub-beta       
```

Fedora 32 (Workstation Edition)
```
❯ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

The previous version was working smoothly

**Comment by PureTryOut** [comment] 2021-01-02 14:07
I just installed OBS from Flathub and I sadly can reproduce this issue. Currently the application is unusable because of it.

**Comment by GeorgesStavracas** [comment] 2021-04-19 01:17
Can you please try running:

```
$ flatpak run --env=MESA_LOADER_DRIVER_OVERRIDE=iris com.obsproject.Studio
```
if this ^^^ doesn't work, try this one:

```
$ flatpak run --env=MESA_LOADER_DRIVER_OVERRIDE=i965 com.obsproject.Studio
```

if this ^^^ doesn't work, try this one:

```
$ flatpak run --env=MESA_LOADER_DRIVER_OVERRIDE=i915 com.obsproject.Studio
```

Does any of them work?

**Comment by hkaancaliskan** [comment] 2022-01-28 12:04
@GeorgesStavracas none of them worked for me.
Silverblue 35 (flatpak version was giving same error on workstation version but rpm version was working great)
UHD 620 iGPU
MX130 dGPU

**Comment by neildarlow** [comment] 2022-02-04 12:55
Hi,

I don't know if this is relevant or the same issue but I receive this error from OBS Sudio 27.1.3 after the update of org.freedesktop.Platform from 21.08.09 to 21.08.10.

None of the previously described MESA_DRIVER_OVERRIDE settings permits the application to start.

I am running GNOME 41.3 on fedora 35 Silverblue edition.

**Comment by bdaase** [comment] 2022-02-04 21:32
Exact same error as @neildarlow on my side. The rpm starts just fine.

**Comment by FastOSlinux** [comment] 2022-02-04 23:52
the same is happening for AMDGPU 

Fedora Silverblue 35

$ flatpak run com.obsproject.Studio 
QSocketNotifier: Can only be used with threads started with QThread
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /app/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /app/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/pt-BR.ini
Attempted path: /app/share/obs/obs-studio/locale/pt-BR.ini
info: Using preferred locale 'pt-BR'
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /app/share/obs/obs-studio/themes/Dark.qss
info: Platform: Wayland
info: CPU Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
info: CPU Speed: 4395.062MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15928MB Total, 6645MB Free
info: Kernel Version: Linux 5.15.16-200.fc35.x86_64
info: Distribution: "KDE Flatpak runtime" "5.15-21.08"
info: Session Type: wayland
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /app/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.1.3 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
error: eglGetDisplay failed
error: device_create (GL) failed
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
qt.qpa.wayland: EGL not available

**Comment by GeorgesStavracas** [comment] 2022-02-05 00:05
This seems to be a Mesa regression that ended up reaching the FreeDesktop platform - see https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1390.

I'll close this since it's already being tracked in the issue linked above.

**Closed by GeorgesStavracas** 2022-02-05 00:05 UTC

**Comment by GeorgesStavracas** [comment] 2022-02-05 00:06
For now, you can downgrade to a previous version of Mesa by running:

```
$ flatpak update --commit=86a1c8526bda603bdfadaaa0c3c76a1afcebf75ad1706c25fee3160765650a13 org.freedesktop.Platform.GL.default//21.08
```

This should work until an update with a working Mesa reaches Flathub.

**Comment by neildarlow** [comment] 2022-02-06 11:15
This appears to be fixed with commit https://github.com/flathub/com.obsproject.Studio/commit/ef97b9e6f0f70060c5cae317664bdb46c2d088bf

**Comment by ernstp** [comment] 2022-02-06 12:56
It was fixed by rebuilding the KDE runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1390#note_832956493

**Comment by neildarlow** [comment] 2022-02-06 14:08
Ah, OK. I wasn't notified that org.kde.Platform had been updated on my system. I really wish that flatpak history command worked to observe these things.
